version: '3.7'

services:
  book-service:
    image: 'book-service'
    build:
      context: book-service/
    depends_on:
      - postgres-db
    ports:
      - "8015:8080"
    networks:
      - to-read-network

  postgres-db:
    image: 'postgres:14.1-alpine'
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    networks:
      - to-read-network
    volumes:
      - db:/var/lib/postgresql/data

networks:
  to-read-network:
    driver: bridge

volumes:
  db:
    driver: local